sudo: false

os:
 - linux

language: d

d:
 - dmd-2.090.0,dub
 - dmd-2.089.1,dub
 - ldc-1.19.0,dub
 - ldc-1.18.0,dub

matrix:
  fast_finish: true
  allow_failures:
   - d: dmd-2.089.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
