sudo: false

os:
 - linux

language: d

d:
 - dmd-2.094.0
 - dmd-2.093.1
 - ldc-1.23.0
 - ldc-1.22.0

matrix:
  fast_finish: true

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
