sudo: false

os:
 - linux

language: d

d:
 - dmd-2.093.0,dub
 - dmd-2.092.1,dub
 - ldc-1.22.0,dub
 - ldc-1.21.0,dub

matrix:
  fast_finish: true

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
