sudo: false

os:
 - linux

language: d

d:
 - dmd-2.082.0
 - ldc-1.11.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
