name: CI

on: 
  push:
    branches: [ master ]
    paths:
    - 'src/*'
    - 'extensions/*'
    - 'shaders/*'
    - 'dub.json'
    - '.github/workflows/*'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/*'
    - 'extensions/*'
    - 'shaders/*'
    - 'dub.json'
    - '.github/workflows/*'

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [windows-latest]
        dc: [dmd-2.094.2, ldc-1.24.0]
        include:
          - os: ubuntu-latest
            dc: dmd-2.094.2
            experimental: true
          - os: ubuntu-latest
            dc: ldc-1.24.0
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub test
